spring.application.name=SnapEat_backend
server.port=8000

# Database Properties
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# App Properties
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.jwt.reset-token-expiry-ms=3600000
app.name=SnapEat
app.frontend-url=https://snapeat.ddns.net
app.support-email=snapeatroos@gmail.com

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=snapeatroos@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# AWS S3 Configuration
aws.s3.bucket=snapeat-storage-2026
aws.s3.region=ap-south-1
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}

logging.level.org.springframework.security=TRACE

# Stripe Payment Configuration
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.publishable-key=${STRIPE_PUB_KEY}
stripe.webhook-secret=dummmy
stripe.currency=inr
