spring.application.name=SnapEat_backend

spring.datasource.url=jdbc:postgresql://ep-polished-unit-a1kw5cxj-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_hRQV7q1GbBED&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=Q2kJfFGdPxEcYDqyEmvm2R6LdIeCeribs2NwU3kxgnEagUNl96WnVmnYqeKcnR6ytdAgIaxBpQxG2Dk86tFKCg==
app.jwt.expiration-ms=86400000
app.jwt.reset-token-expiry-ms=3600000

app.name=SnapEat
app.frontend-url=http://localhost:5173
app.support-email=snapeatroos@gmail.com
