name: Deploy Frontend
on:
  push:
    branches: [ development ] # Runs every time you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development

      - name: Install & Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*" # Or "build/*" depending on your React setup
          target: "/var/www/html" # Nginx default folder
          strip_components: 1
