name: Deploy Frontend
on:
  push:
    branches: [ development ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development

      - name: Install & Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Prepare dist for SCP
        run: cp -r frontend/dist ./dist

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist"
          target: "/var/www/html"
          strip_components: 1
